[build-system]
requires = ["setuptools>=70", "wheel", "build"]
build-backend = "setuptools.build_meta"

[project]
name = "pydriosm"
dynamic = [
    "version",
    "description",
    "urls",
    "authors",
    "license"
]
readme = { file = "README.md", content-type = "text/markdown" }
keywords = [
    "Python",
    "OpenStreetMap",
    "OSM",
    "Geofabrik",
    "BBBike",
    "Protocolbuffer Binary Format",
    "PBF",
    "Shapefile",
    "PostgreSQL"
]
requires-python = ">=3.12"
dependencies = [
    "pyhelpers ~= 2.4.0",
    "pyrcs ~= 1.1.0",
    "pyshp >= 3.0.3",
]
classifiers = [
    "Intended Audience :: Developers",
    "Intended Audience :: Education",
    "Intended Audience :: Science/Research",
    "Topic :: Database",
    "Topic :: Database :: Database Engines/Servers",
    "Topic :: Education",
    "Topic :: Scientific/Engineering",
    "Topic :: Software Development",
    "Topic :: Utilities",
    "Programming Language :: Python :: 3",
    "Operating System :: Microsoft :: Windows",
    "Operating System :: POSIX :: Linux",
]

[tool.setuptools]
packages = { find = {} }
