# Configuration file for the Sphinx documentation builder.

import datetime
import os
import sys

""" Path setup """

# If the directory is relative to the documentation root, use os.path.abspath to make it absolute, like shown here.
sys.path.insert(0, os.path.abspath('../..'))
sys.path.insert(0, os.path.abspath('../../pydriosm'))
sys.path.insert(0, os.path.abspath('../../pydriosm/download'))
sys.path.insert(0, os.path.abspath('../../pydriosm/read'))
sys.path.insert(0, os.path.abspath('../../pydriosm/io'))
# If extensions (or modules to document with autodoc) are in another directory, add these directories to sys.path here.

import pydriosm

""" Project information """

# General information about the project.
project = 'pydriosm'
copyright = '2019-{}, {}'.format(datetime.datetime.now().year, pydriosm.__author__)

""" The version info for the project """

# The short X.Y version.
version = pydriosm.__version__

# The full version, including alpha/beta/rc tags.
release = version

""" General configuration """

# Sphinx extension module names, which can be extensions coming with Sphinx (named 'sphinx.ext.*') or custom ones.
extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.viewcode',
    'sphinx.ext.autosummary',
    'sphinx.ext.autosectionlabel',
    'sphinx.ext.extlinks',
    'sphinx.ext.intersphinx',
    'sphinx.ext.inheritance_diagram',
    'sphinx.ext.githubpages',
    'sphinx_rtd_theme'
]

# The language for content autogenerated by Sphinx
language = 'en'

# List of patterns, relative to source directory, that match files and directories to ignore
exclude_patterns = ['_build', '../_build', '../build']

# Whether to scan all found documents for autosummary directives, and to generate stub pages for each
autosummary_generate = True

# A list of modules to be mocked up
autodoc_mock_imports = []

# The suffix(es) of source filenames (For multiple suffix, a list of string, e.g. source_suffix = ['.rst', '.md'])
source_suffix = '.rst'

# The master toctree document.
master_doc = 'index'

# Automatically documented members are sorted by source order ('bysource')
autodoc_member_order = 'bysource'

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

""" Options for HTML and HTMLHelp output """

# The theme to use for HTML and HTML Help pages.
html_theme = 'sphinx_rtd_theme'  # or 'sphinxdoc', 'default', 'nature', ...

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'  # or 'default'

# Paths that contain custom static files (such as style sheets), relative to this directory.
html_static_path = ['_static']

# Output file base name for HTML help builder. Default is 'pydoc'.
htmlhelp_basename = project + 'doc'

""" Options for LaTeX output """

# The LaTeX engine to build the docs
latex_engine = 'pdflatex'

# Grouping the document tree into LaTeX files
latex_documents = [
    ('index',  # source start file
     'pydriosm.tex',  # target name
     'PyRCS Documentation',  # title
     'Qian Fu',  # author
     'manual',  # document class ['howto', 'manual', or own class]
     1  # toctree only
     ),
]

# LaTeX customization
latex_elements = {
    'papersize': 'a4paper',  # The paper size ('letterpaper' or 'a4paper').
    'pointsize': '10pt',  # The font size ('10pt', '11pt' or '12pt').
    'pxunit': '0.25bp',
    'preamble': r'''
        \setlength{\headheight}{14pt}
        \DeclareUnicodeCharacter{229E}{\ensuremath{\boxplus}}
        \usepackage[utf8]{inputenc}
        \usepackage{textcomp}
        \usepackage{amsfonts}
        \usepackage{textgreek}
        \usepackage{graphicx}
        \usepackage{svg}
        ''',
    'printindex': r'''
        \IfFileExists{\jobname.ind}
                     {\footnotesize\raggedright\printindex}
                     {\begin{sphinxtheindex}\end{sphinxtheindex}}
    ''',
    'passoptionstopackages': r'\PassOptionsToPackage{svgnames}{xcolor}',
    'fvset': r'\fvset{fontsize=auto}',
    'figure_align': 'H'  # Latex figure (float) alignment
}

# The theme that the LaTeX output should use
latex_theme = 'manual'

""" Options for manual page output """

# How to group the document tree into manual pages
man_pages = [
    ('index',  # startdocname
     'pydriosm',  # name
     'PyRCS Documentation',  # description
     ['Qian Fu'],  # authors
     1  # section
     )
]

""" Options for Texinfo output """

# Grouping the document tree into Texinfo files
texinfo_documents = [
    (master_doc,  # source start file
     'pydriosm',  # target name
     'PyRCS Documentation',  # title
     'Qian Fu',  # author
     'PyRCS',  # dir menu entry
     'A toolkit for facilitating data manipulation using Python.',  # description
     'Data manipulation tools',  # category
     1  # toctree only
     ),
]
